name: React App CI/CD with ArgoCD

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: 809691348554.dkr.ecr.ap-northeast-2.amazonaws.com/team03-fe-repository
  IMAGE_TAG: latest
  EKS_CLUSTER_NAME: msa
  ARGOCD_APP_NAME: team03-fe
  ARGOCD_SERVER: argocd-server.argocd

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write    # GitHub OIDC 토큰에 필요한 권한

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache-dependency-path: '**/package.json'   # lock 파일을 사용하지 않도록 수정

      - name: Install dependencies
        run: npm install

      - name: Build React application
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}} .
          docker push ${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
          # 이미지 URI를 출력하여 다음 단계에서 사용
          echo "image=${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}" >> $GITHUB_OUTPUT

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update Kubernetes config
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64

      - name: Login to ArgoCD
        run: |
          argocd login ${{ env.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --insecure

      - name: Update Deployment Image in ArgoCD
        run: |
          # 이미지 태그 업데이트
          argocd app set ${{ env.ARGOCD_APP_NAME }} -p image.tag=${{ github.sha }}
          
          # 변경 사항 동기화
          argocd app sync ${{ env.ARGOCD_APP_NAME }} --prune

      - name: Verify Deployment
        run: |
          argocd app wait ${{ env.ARGOCD_APP_NAME }} --health --timeout 300